function output=ReKai(Q,WW,mutilde)

W=abs(WW);

% With singularities
output= 1./pi .* (-2.*log(1+exp(mutilde)) -2.*log(1+exp(-mutilde)) + ...
         Theta(W-Q) .* Q.^2 ./(2.*sqrt(W.^2-Q.^2)) .* ...
         ( (Gminus(Q,W,1,mutilde)+Gminus(Q,W,-1,mutilde)) - (Gplus(Q,W,1,mutilde)+Gplus(Q,W,-1,mutilde))  ) + ...
         Theta(Q-W) .* Q.^2 ./(2.*sqrt(Q.^2-W.^2) ) .* (-pi./2 +Hminus(Q,W,1,mutilde) + Hminus(Q,W,-1,mutilde) ) ... 
            );

end